
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-rec-f24-08
owner: ucsb-cs156-f24
repo_name: proj-rec-f24-08
pull_requests: [{"author":{"id":"U_kgDOCMNTCg","is_bot":false,"login":"Mike-Petrus","name":""},"headRefName":"Mike-CreateRecReqTable","number":35,"title":"Mike - E11-B1: Create rec req table","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/35"},{"author":{"id":"U_kgDOBcsiCw","is_bot":false,"login":"obenedek20","name":""},"headRefName":"Oscar-ElimRestaurantFrontend","number":32,"title":"Oscar - Eliminated Frontend for UCSBDates and Restaurants","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/32"}]
