
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-rec-f24-08
owner: ucsb-cs156-f24
repo_name: proj-rec-f24-08
pull_requests: [{"author":{"id":"U_kgDOBcsiCw","is_bot":false,"login":"obenedek20","name":""},"headRefName":"Oscar-EditRequestPage","number":54,"title":"Oscar - Edit Page Implemented","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/54"},{"author":{"id":"U_kgDOBcsiCw","is_bot":false,"login":"obenedek20","name":""},"headRefName":"Oscar-CreateRequestPage","number":52,"title":"Oscar - Create Page implemented for Recommendation Requests","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/52"},{"author":{"id":"U_kgDOBcsiCw","is_bot":false,"login":"obenedek20","name":""},"headRefName":"Oscar-FormComponent","number":50,"title":"Oscar- Form Component for Recommendation Requests","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/50"},{"author":{"id":"U_kgDOBcsiCw","is_bot":false,"login":"obenedek20","name":""},"headRefName":"Oscar-Fixtures","number":48,"title":"Oscar - Creates Fixtures for Recommendation Requests","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/48"},{"author":{"id":"U_kgDOBcsiCw","is_bot":false,"login":"obenedek20","name":""},"headRefName":"Oscar-ElimRestaurantFrontend","number":42,"title":"Oscar - Eliminates Restaurant, UCSBDates frontend components","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/42"},{"author":{"id":"U_kgDOBcsiCw","is_bot":false,"login":"obenedek20","name":""},"headRefName":"Oscar-ElimRestaurantBackend","number":41,"title":"Oscar - Eliminates references to Restaurants, UCSBDates, and UCSBDiningCommons","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/41"},{"author":{"id":"MDQ6VXNlcjUzMjc5MDkx","is_bot":false,"login":"qwistaycat","name":"Christy Yu"},"headRefName":"cy-CRUD-operations","number":39,"title":"CY-Epic11-B2","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/39"},{"author":{"id":"MDQ6VXNlcjY4MDg2NzYw","is_bot":false,"login":"yw2398","name":"Amber Wang"},"headRefName":"AW-Placeholder-ProfessorPages","number":38,"title":"AW-Epic14-F1: Added placeholders for professor pages","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/38"},{"author":{"id":"U_kgDOCMNTCg","is_bot":false,"login":"Mike-Petrus","name":""},"headRefName":"Mike-CreateRecReqTable","number":35,"title":"Mike - E11-B1: Create rec req table","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/35"}]
