
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-rec-f24-08
owner: ucsb-cs156-f24
repo_name: proj-rec-f24-08
pull_requests: [{"author":{"id":"U_kgDOCu01tQ","is_bot":false,"login":"divyanipunj","name":""},"headRefName":"dp-recreq-index","number":75,"title":"divyani - Added INDEX page for Recommendation Request","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/75"},{"author":{"id":"U_kgDOBcsiCw","is_bot":false,"login":"obenedek20","name":""},"headRefName":"Oscar-RequestEditPage","number":74,"title":"Oscar - Recommendation Request Edit Page","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/74"},{"author":{"id":"U_kgDOBcsiCw","is_bot":false,"login":"obenedek20","name":""},"headRefName":"Oscar-RequestCreatePage","number":73,"title":"Oscar - Create Page for Recommendation Requests","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/73"},{"author":{"id":"U_kgDOBcsiCw","is_bot":false,"login":"obenedek20","name":""},"headRefName":"Oscar-RequestForm","number":72,"title":"Oscar - Form Component for Recommendation Requests (redo of old PR after controller changes)","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/72"},{"author":{"id":"U_kgDOCu01tQ","is_bot":false,"login":"divyanipunj","name":""},"headRefName":"dp-recommendationrequest-delete_postREDO","number":68,"title":"divyani - Added DELETE and PUT operations (plus tests) for RecommendationRequest","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/68"},{"author":{"id":"U_kgDOBcsiCw","is_bot":false,"login":"obenedek20","name":""},"headRefName":"Oscar-GETPOST","number":66,"title":"Oscar - GET and POST routes for RecommendationRequest, database changes","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/66"}]
