
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-rec-f24-08
owner: ucsb-cs156-f24
repo_name: proj-rec-f24-08
pull_requests: [{"author":{"id":"MDQ6VXNlcjUzMjc5MDkx","is_bot":false,"login":"qwistaycat","name":"Christy Yu"},"headRefName":"cy-Completed-Requests-Page","number":81,"title":"Christy - completed requests page","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/81"},{"author":{"id":"U_kgDOBcsiCw","is_bot":false,"login":"obenedek20","name":""},"headRefName":"Oscar-POSTChange","number":79,"title":"Oscar - POST Change to check recommendation types against database","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/79"},{"author":{"id":"U_kgDOCu01tQ","is_bot":false,"login":"divyanipunj","name":""},"headRefName":"dp-recreq-index","number":75,"title":"divyani - Added INDEX page for Recommendation Request","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-08/pull/75"}]
